spring.application.name=bank-upi-switch

# Puerto HTTP donde escuchará el Switch (Para cuando simulemos el Fake Lambda más adelante)
server.port=8080

# ---------------------------------------------------------
# gRPC Client Configuration (El Directorio)
# ---------------------------------------------------------
# Le decimos al cliente gRPC llamado 'account-mapper' dónde conectarse
grpc.client.account-mapper.address=static://localhost:9090
# Desactivamos seguridad TLS temporalmente para pruebas locales
grpc.client.account-mapper.negotiation-type=plaintext