#nombre de la aplicación - para trazar en logs y métricas
spring.application.name=account-mapper-service

#desactivamos el servidor web, ya que este servicio no expone endpoints HTTP (rest)
spring.main.web-application-type=none

#puerto donde escuchará nuestro servidor gRPC (HTTP/2)
grpc.server.port=9090